dataset:
  path_xes: "data/Hospital_log.xes.gz"
  path_dataset: "data/dataset-pe.pt"
  path_labels: "data/labels.json"
  path_metadata: "data/metadata-pe.json"
  exclude_attributes:
    - "ocel:eid"
    - "ocel:timestamp"
    - "ocel:oid"
    - "ocel:type"
    - "case:End date"
    - "case:Start date"
    - "case:End date:1"
    - "case:Start date:1"
    - "case:End date:2"
    - "case:Start date:2"
    - "case:End date:3"
    - "case:Start date:3"
    - "case:End date:4"
    - "case:Start date:4"
    - "case:End date:5"
    - "case:Start date:5"
    - "case:End date:6"
    - "case:Start date:6"
    - "case:End date:7"
    - "case:Start date:7"
    - "case:End date:8"
    - "case:Start date:8"
    - "case:End date:9"
    - "case:Start date:9"
    - "case:End date:10"
    - "case:Start date:10"
    - "case:End date:11"
    - "case:Start date:11"
    - "case:End date:12"
    - "case:Start date:12"
    - "case:End date:13"
    - "case:Start date:13"
    - "case:End date:14"
    - "case:Start date:14"
    - "case:End date:15"
    - "case:Start date:15"
  normalize: True
  one_hot_encoding: True

process_execution:
  viewpoint: "case:concept:name"

gnn:
  path_model: "data/model-pe.pth"
  homogeneous: True
  unique_node_type_attribute_columns: True
  num_layers: 1
  batch_size: 10
  dropout: 0.1
  n_epochs: 100
  start_patience: 25
  learning_rate: 0.01

counterfactual:
  # viewpoint_id: "00000001"
  viewpoint_label: False
  depth_first: "attribute"
  num_bins: 2
  max_change_size: 3
  node_importance_threshold: 0
  attr_importance_threshold: 0
