dataset:
  path_ocel: "data/container_logistics.json"
  path_dataset: "data/dataset-pe.pt"
  path_labels: "data/labels.json"
  path_metadata: "data/metadata-pe.json"
  exclude_attributes:
    - "ocel:eid"
    - "ocel:timestamp"
    - "ocel:oid"
    - "ocel:type"
    - "DepartureDate"
  normalize: True
  one_hot_encoding: True
  add_reverse_edges: True

process_execution:
  viewpoint: "Customer Order"
  viewpoint_activity: "Register Customer Order"
  object_types:
    - "Customer Order"
    - "Transport Document"
    - "Handling Unit"
    - "Container"
  trace_backward: False

gnn:
  path_model: "data/model-pe.pth"
  homogeneous: True
  num_layers: 5
  batch_size: 20
  dropout: 0.3
  n_epochs: 200
  start_patience: 80
  learning_rate: 0.01
  random_seed: 42

counterfactual:
  # verbose: True
  viewpoint_label: False
  depth_first: "node"
  num_bins: 2
  max_change_size: 3
  node_importance_threshold: 0.01
  attr_importance_threshold: 0.01

counterfactual_graphcfe:
  path_model: "data/model_graphcfe.pth"
  vae_type: "graphVAE"
  dim_h: 64
  dim_z: 32
  dropout: 0.1
  disable_u: False
  batch_size: 10
  n_epochs: 200
  learning_rate: 0.01
  patience: 40
