dataset:
  path_xes: "data/Road_Traffic_Fine_Management_Process.xes.gz"
  path_dataset: "data/dataset-pe.pt"
  path_metadata: "data/metadata-pe.json"
  path_sample: "data/sample_objects.txt"
  exclude_attributes:
    - "ocel:eid"
    - "ocel:timestamp"
    - "ocel:oid"
    - "ocel:type"
  normalize: True
  one_hot_encoding: True

process_execution:
  viewpoint: "case:concept:name"

gnn:
  path_model: "data/model-pe.pth"
  num_layers: 1
  dropout: 0.1
  n_epochs: 100
  start_patience: 25
  learning_rate: 0.01

counterfactual:
  viewpoint_object_id: "A10068"
  depth_first: "node"
  num_bins: 2
  max_change_size: 5
  node_importance_threshold: 0.01
  attr_importance_threshold: 0.05
