dataset:
  path_ocel: "data/socel_hinge.json"
  path_dataset: "data/dataset-pe-MalePart.pt"
  path_labels: "data/labels-MalePart.json"
  path_metadata: "data/metadata-pe-MalePart.json"
  exclude_attributes:
    - "ocel:eid"
    - "ocel:timestamp"
    - "ocel:oid"
    - "ocel:type"
  normalize: True
  one_hot_encoding: True
  add_reverse_edges: True

process_execution:
  viewpoint: "MalePart"
  viewpoint_activity: "CheckMalePart"
  object_types:
    - "FormedPart"
    - "MalePart"
    - "SteelPin"
    - "SteelSheet"
    - "SteelCoil"
  target_activity: "SplitSteelSheet"
  trace_backward: True

gnn:
  path_model: "data/model-pe-MalePart.pth"
  homogeneous: True
  num_layers: 2
  batch_size: 10
  dropout: 0.3
  n_epochs: 100
  start_patience: 50
  learning_rate: 0.001

counterfactual:
  # viewpoint_id: "e_checkMale_2906>true"
  viewpoint_label: False
  # depth_first: "attribute"
  num_bins: 2
  max_change_size: 3
  node_importance_threshold: 0.01
  attr_importance_threshold: 0.1

counterfactual_graphcfe:
  path_model: "data/model_graphcfe-MalePart.pth"
  vae_type: "graphVAE"
  dim_h: 64
  dim_z: 32
  dropout: 0.1
  disable_u: False
  batch_size: 10
  n_epochs: 300
  learning_rate: 0.01
  patience: 25
