dataset:
  path_ocel: "data/socel_hinge.json"
  path_dataset: "data/dataset-pe-HingePack.pt"
  path_labels: "data/labels-HingePack.json"
  path_metadata: "data/metadata-pe-HingePack.json"
  exclude_attributes:
    - "ocel:eid"
    - "ocel:timestamp"
    - "ocel:oid"
    - "ocel:type"
  normalize: True
  one_hot_encoding: True
  add_reverse_edges: True

process_execution:
  viewpoint: "HingePack"
  viewpoint_activity: "PackHinges"
  object_types:
    - "FormedPart"
    - "Hinge"
    - "HingePack"
    - "MalePart"
    - "SteelPin"
    - "SteelSheet"
    - "SteelCoil"
  target_activity: "SplitSteelSheet"
  trace_backward: True

gnn:
  path_model: "data/model-pe-HingePack.pth"
  homogeneous: True
  num_layers: 5
  batch_size: 20
  dropout: 0.3
  n_epochs: 200
  start_patience: 80
  learning_rate: 0.01
  random_seed: 42

counterfactual:
  # verbose: True
  # viewpoint_id: "e_packhinges_142"
  viewpoint_label: False
  depth_first: "node"
  num_bins: 2
  max_change_size: 3
  node_importance_threshold: 0.0001
  attr_importance_threshold: 0.01
  # category_importance_threshold: 0.01

counterfactual_graphcfe:
  path_model: "data/model_graphcfe-HingePack.pth"
  vae_type: "graphVAE"
  dim_h: 64
  dim_z: 32
  dropout: 0.1
  disable_u: False
  batch_size: 10
  n_epochs: 200
  learning_rate: 0.01
  patience: 40
