dataset:
  path_ocel: "data/socel_hinge.json"
  path_dataset: "data/dataset-pe-MalePart.pt"
  path_metadata: "data/metadata-pe-MalePart.json"
  exclude_attributes:
    - "ocel:eid"
    - "ocel:timestamp"
    - "ocel:oid"
    - "ocel:type"
  normalize: True
  one_hot_encoding: True

process_execution:
  viewpoint: "MalePart"
  viewpoint_activity: "CheckMalePart"
  object_types:
    - "FormedPart"
    - "MalePart"
    - "SteelPin"
    - "SteelSheet"
    - "SteelCoil"
  target_activity: "SplitSteelSheet"
  trace_backward: True

gnn:
  path_model: "data/model-pe-MalePart.pth"
  num_layers: 1
  batch_size: 10
  dropout: 0.1
  n_epochs: 100
  start_patience: 25
  learning_rate: 0.01

counterfactual:
  viewpoint_event_id: "e_checkMale_2906>true"
  depth_first: "node"
  num_bins: 2
  max_change_size: 5
  node_importance_threshold: 0.01
  attr_importance_threshold: 0.1
